"""Local language-model abstractions and response validation."""

from polis.llm.adapter import (
    BackendRequest,
    BackendRetryPolicy,
    LocalBackendTransport,
    MockHeuristicBackend,
    MockHeuristicTransport,
    create_default_local_backend,
)
from polis.llm.contracts import (
    LLM_PROMPT_VERSION,
    LLM_RESPONSE_SCHEMA_VERSION,
    LLMFindingInput,
    build_prompt,
    validate_llm_response,
)
from polis.llm.corrected_text import (
    DiagnosticPromptVariant,
    DiagnosticRoute,
    FiniteCandidate,
    PromptRequest,
    SpecialistFocus,
    TextEdit,
    build_diagnostic_prompt_request,
    build_evidence_bound_corrected_text_prompt_request,
    build_inflection_candidate_prompt_request,
    build_proposal_verifier_prompt_request,
    build_specialist_corrected_text_prompt,
    build_specialist_corrected_text_prompt_request,
    derive_text_edits,
    validate_candidate_selection_response,
    validate_corrected_text_response,
    validate_diagnostic_response,
    validate_evidence_bound_corrected_text_response,
    validate_verifier_response,
)

__all__ = [
    "LLM_PROMPT_VERSION",
    "LLM_RESPONSE_SCHEMA_VERSION",
    "LLMFindingInput",
    "build_prompt",
    "validate_llm_response",
    "BackendRequest",
    "BackendRetryPolicy",
    "LocalBackendTransport",
    "MockHeuristicBackend",
    "MockHeuristicTransport",
    "create_default_local_backend",
    "DiagnosticPromptVariant",
    "DiagnosticRoute",
    "FiniteCandidate",
    "PromptRequest",
    "SpecialistFocus",
    "TextEdit",
    "build_diagnostic_prompt_request",
    "build_evidence_bound_corrected_text_prompt_request",
    "build_inflection_candidate_prompt_request",
    "build_proposal_verifier_prompt_request",
    "build_specialist_corrected_text_prompt",
    "build_specialist_corrected_text_prompt_request",
    "derive_text_edits",
    "validate_candidate_selection_response",
    "validate_corrected_text_response",
    "validate_diagnostic_response",
    "validate_evidence_bound_corrected_text_response",
    "validate_verifier_response",
]
