"""Core public model boundary."""

from polis.core.models import (
    AnalysisOptions,
    AnalysisResult,
    AnalysisTimeoutError,
    BackendUnavailableError,
    Category,
    Confidence,
    ConfigurationError,
    CorrectionConflictError,
    CorrectionSelectionError,
    Finding,
    InvalidBackendResponseError,
    PolisError,
    Severity,
    Source,
    SourceKind,
    UncorrectableFindingError,
    UnknownFindingError,
)
from polis.core.protocols import (
    AnalysisOrchestrator,
    DeterministicAnalyzer,
    LocalFindingBackend,
    LocalGenerationBackend,
    MonotonicClock,
    Rule,
    RuleRegistry,
)
from polis.core.serialization import (
    ANALYSIS_SCHEMA_VERSION,
    analysis_result_from_json,
    analysis_result_to_json,
)

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "AnalysisOrchestrator",
    "AnalysisOptions",
    "AnalysisResult",
    "Category",
    "Confidence",
    "DeterministicAnalyzer",
    "Finding",
    "LocalFindingBackend",
    "LocalGenerationBackend",
    "MonotonicClock",
    "Rule",
    "RuleRegistry",
    "PolisError",
    "AnalysisTimeoutError",
    "BackendUnavailableError",
    "ConfigurationError",
    "InvalidBackendResponseError",
    "CorrectionSelectionError",
    "UnknownFindingError",
    "UncorrectableFindingError",
    "CorrectionConflictError",
    "Severity",
    "Source",
    "SourceKind",
    "analysis_result_from_json",
    "analysis_result_to_json",
]
